syntax on
set cc=100
colorscheme default

set backspace=indent,eol,start
set mouse=a
set hlsearch
set incsearch
set ignorecase
set number
set ruler
set nowrap
set scrolloff=10
let g:mapleader=" "

set autoindent
set noexpandtab    " disable converting between tabs and spaces
set softtabstop=-1 " for when deleting (-1 to follow shiftwidth)
set shiftwidth=0   " for autoindent (0 to follow tabstop)
set tabstop=2      " how many spaces to view a tab as

" windows
noremap <C-K> <C-W>k
noremap <C-J> <C-W>j
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l
noremap <C-E> <C-W>=
noremap <leader>+ 10<C-W>+
noremap <leader>- 10<C-W>-
noremap <leader>> 10<C-W>>
noremap <leader>< 10<C-W><

" buffers
"set switchbuf=useopen
nnoremap <C-N> :bn<CR> " next
nnoremap <C-P> :bp<CR> " previous
nnoremap <C-L> :b#<CR> " last
