syntax on
set cc=100
colorscheme default

set backspace=indent,eol,start
set mouse=a
set hlsearch
set incsearch
set number
set ruler
set nowrap
set scrolloff=10
let g:mapleader=" "

set autoindent
set noexpandtab    " disable converting between tabs and spaces
set softtabstop=-1 " for when deleting (-1 to follow shiftwidth)
set shiftwidth=0   " for autoindent (0 to follow tabstop)
set tabstop=2      " how many spaces to view a tab as

" windows
noremap <C-K> <C-W>k
noremap <C-J> <C-W>j
noremap <C-H> <C-W>h
noremap <C-L> <C-W>l
"noremap <C-P> <C-W>p
noremap <Up> 10<C-W>+
noremap <Down> 10<C-W>-
noremap <Right> 10<C-W>>
noremap <Left> 10<C-W><
noremap <C-E> <C-W>=

" buffers
"set switchbuf=useopen
"nnoremap <C-N> :bn<CR>
"nnoremap <C-P> :bp<CR>
nnoremap <C-P> :b#<CR>
"nnoremap <leader>a :sb#<CR>
